### ISSUE TITLE
[Feature] Curios API Support

### ISSUE THREAD

**Issue by japa4551** [henkelmax/gravestone#62] opened 2021-05-25 23:48 UTC
**Is your feature request related to a problem? Please describe.**
Every time that i die with a Curios Supported Item equipped, the item goes back to my inventory instead of the Curios Slot

**Describe the solution you'd like**
Instead of the item going back to the inventory, it is equipped right back on the Curios Slot

**Additional context**
I've lost a few items due to this problem, i think it would be a nice addition more than welcome in big modpacks

EDIT: The items that were tested are from the mod "Artifacts" v2.8.3 by ochotonida

**Comment by henkelmax** [comment] 2021-05-26 06:59
Duplicate of #37

**Closed by henkelmax** 2021-05-26 06:59 UTC
Labels: enhancement
