### ISSUE TITLE
Payload error when deleting Obituary using trash slot

### ISSUE THREAD

**Issue by Rithenar** [henkelmax/gravestone#3] opened 2020-08-30 16:39 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/gravestone/faq) before submitting a bug report!**

**Bug description**
When using the inventory trash slot from TrashSlot mod to destroy an Obituary client disconnects from server  and I get the following error

![image](https://user-images.githubusercontent.com/9939332/91664335-1ffe6500-eab4-11ea-9f9f-2fb1ae1ea73e.png)

**Steps to reproduce the issue**
1. Die and get an obituary
2. Put Obituary on inventory Trash Slot
3. Crash

**Expected behavior**
not to crash when I delete the obituary

**Log files**
https://paste.ee/p/qxVj2

**Versions**
- Minecraft version 1.15.2
- Forge version 31.2.36
- Mod version 1.17.5

**Other mods**
Mods from TNP Limitless 2  https://www.curseforge.com/minecraft/modpacks/tnp-limitless-2/relations/dependencies

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment] 2020-08-30 16:45
> Log files
https://paste.ee/p/qxVj2

There doesn't seem to be any crash in this log.
Please send me the correct logs.

**Comment by Rithenar** [comment] 2020-08-30 16:47
I don't believe the client is crashing as I am getting no crash reports anywhere. It is just disconnecting from server with that error code. All logs I can see in the "logs" folder in MultiMc are 
![image](https://user-images.githubusercontent.com/9939332/91664716-a0be6080-eab6-11ea-80b8-4ad5448ba3c7.png)

**Comment by henkelmax** [comment] 2020-08-30 16:57
It seems that the error is caused by `TrashSlot` sending a network packet to the server containing the item stack you want to delete.
The obituary contains all items of your inventory. This means if you have a lot of items or NBT data in your inventory when you die, the obituary item is too large to send it to the server.
This issue can be fixed by not sending the actual item stack in the packet.

This seems to be the packet that causes the issue:
https://github.com/blay09/TrashSlot/blob/2c87c934b58b880c4d33e15303097917e01fa90e/src/main/java/net/blay09/mods/trashslot/network/MessageTrashSlotClick.java#L22

> I don't believe the client is crashing as I am getting no crash reports anywhere. It is just disconnecting from server with that error code. All logs I can see in the "logs" folder in MultiMc are

You are right. It is actually the server throwing the error, because it checks for the size of the packet that the client sends.

The best way to solve this issue is to report this bug to the `TrashSlot` developers.
Another option could be to disable the obituary.
If both of these solutions are no option, I could add a config option to disable the item tracking in the obituary.

**Comment by Rithenar** [comment] 2020-08-30 16:59
Thank you for the detailed response henkelmax, and it makes sense. As far as I am concerned I will disable the obituary as I never use it and report it to the TrashSlot developers so they are aware of it.

**Comment by henkelmax** [comment] 2020-08-30 17:20
Thank you very much!
Let me know if there are any updates to this problem.

**Closed by henkelmax** 2020-08-30 17:20 UTC
Labels: bug

**Comment by TheFantasticLoki** [comment] 2020-09-28 21:15
I can confirm this is still happening and because of this I feel like the obituary's could be a SERIOUS issue cause I feel like they can be used to book ban players on multi player servers. Especially if someone were to fill a whole shulker with them.

**Comment by henkelmax** [comment] 2020-09-29 08:32
This is not that much of an issue for a forge mod, as for vanilla Minecraft I think.
