### ISSUE TITLE
Curios compatibility 1.18.2 

### ISSUE THREAD

**Issue by alessandriLuca** [henkelmax/gravestone#124] opened 2022-12-14 07:02 UTC
**Is your feature request related to a problem? Please describe.**
Curios add an additional toolbar to wear item on the back and so on. Would be wonderful an integration with it so anytime I take back my grave everything go back in the same place, also the curios tab.

**Comment by henkelmax** [comment] 2022-12-14 07:03
Duplicate of #119

**Closed by henkelmax** 2022-12-14 07:03 UTC
Labels: enhancement

**Comment by SonicTheHedgehog58987276** [comment] 2023-07-01 01:38
<img width="960" alt="Screenshot 2023-06-30 155354" src="https://github.com/henkelmax/gravestone/assets/115895321/b800035a-699b-481c-93b1-67c7cc5f7aa7">
