### ISSUE TITLE
Curios API Compatibility.

### ISSUE THREAD

**Issue by HeavyDeception** [henkelmax/gravestone#95] opened 2022-05-18 09:13 UTC
**Is your feature request related to a problem? Please describe.**
Allowing the mod to work with Curios API so when picking up your grave it puts your items back in their slots as of right now it just throws them in your inventory or on the ground if you had no room.

**Describe the solution you'd like**
When you pick up your grave your Curios items will go back into their slots.

**Comment by henkelmax** [comment] 2022-05-18 09:24
Duplicate of #37 and #62

**Closed by henkelmax** 2022-05-18 09:24 UTC
Labels: enhancement
