### ISSUE TITLE
No grave or obituary 

### ISSUE THREAD

**Issue by JacButta** [henkelmax/gravestone#20] opened 2020-11-18 14:48 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/gravestone/faq) before submitting a bug report!**

**Bug description**
I just updated my Gravestones mod from 1.16.3 to 1.16.4 , I died in my world, but no grave or obituary was placed. I went into serverconfig and made sure the block I was on was allowed to be replaced by a grave and it was. I tried dying a few times, but nothing ends up there. In creative mode, I see a grave item, and forge detects the mod as being on, but there’s just no grave spawning. I have keep inventory on, but with the previous version it still worked. I am in a Biome made by BOP, but as I stated before, just last night before I updated the mod, I would die and a stone would still pop up. I’m not sure what exactly is causing the issue. 

**Versions**
- Minecraft version : 1.16.4
- Forge version 35.0.15
- Mod version 1.16.4-1.0.3

**Other mods**
Biomes O’ Plenty 1.16.4-13.0.0.418
Optifine 1.16.4 HD U G5

**Comment by henkelmax** [comment] 2020-11-18 15:02
Please send me your log files.
Also please make sure if it happens without BOP.

**Comment by MeinKraft** [comment] 2020-11-24 12:05
Im having similar issue with my modpack on 1.16.3 and version 2.0.4 of the mod - no grave, no death note

but with just forge and grave stone mod it works fine, also tested with forge 1.16.4 35.1.3 and gravestone 1.0.4 and they work fine

so there must be another mod causing issue, well for me anyway - my log indicates problems with cyclic and scaling health

`[11:54:58] [Server thread/ERROR]: Exception caught during firing event: null
	Index: 4
	Listeners:
		0: HIGHEST
		1: ASM: class net.silentchaos512.scalinghealth.event.ScalingHealthCommonEvents onMobXPDropped(Lnet/minecraftforge/event/entity/living/LivingExperienceDropEvent;)V
		2: NORMAL
		3: net.minecraftforge.eventbus.EventBus$$Lambda$2938/182224515@669f3200
		4: ASM: com.lothrazar.cyclic.enchant.EnchantXp@3178ca57 handleEntityDropEvent(Lnet/minecraftforge/event/entity/living/LivingExperienceDropEvent;)V
java.lang.NullPointerException
	at com.lothrazar.cyclic.enchant.EnchantXp.handleEntityDropEvent(EnchantXp.java:37)`

**Comment by henkelmax** [comment] 2020-11-24 12:06
Then please send me your logfiles.

**Comment by MeinKraft** [comment] 2020-11-24 12:18
ive put it on onedrive as its 4mb !  https://1drv.ms/u/s!ArSGAcC04KWspXYpAHV9XPaReHz4?e=lo2gEp  
this is from my BotaniaSkies modpack, forge 34.1.42, GraveStone 2.0.4

I use the kill command to kill me, get "Unexpected error executing command", die, respawn, no grave, no death note
it mentions cyclic nullpointerexception

**Comment by henkelmax** [comment] 2020-11-24 12:26
OK. I found the issue. Please update cyclic to the latest version.
This seems to be a duplicate of #17 
I fixed this cyclic issue in https://github.com/Lothrazar/Cyclic/pull/1573

**Comment by MeinKraft** [comment] 2020-11-24 12:30
Indeed the Cyclic update cures the problem, thank you

**Comment by henkelmax** [comment] 2020-11-24 12:31
No problem!

**Closed by henkelmax** 2020-11-24 12:31 UTC
Labels: bug
